### ISSUE TITLE
[CJB Item Spawner] Mod Menu Open Issue

### ISSUE THREAD

**Issue by ChulkyBow** [CJBok/SDV-Mods#174]
What can I do with this problem?
```
[SMAPI] The CJBItemSpawner.Framework.ItemMenu menu crashed while drawing itself. SMAPI will force it to exit to avoid crashing the game.
ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at StardewValley.Menus.TextBox.Draw(SpriteBatch spriteBatch, Boolean drawShadow) in stardewvalley\Farmer\Farmer\Menus\TextBox.cs:line 228
   at CJBItemSpawner.Framework.ItemMenu.draw(SpriteBatch spriteBatch) in E:\source\_Stardew\Mods.CJBok\CJBItemSpawner\Framework\ItemMenu.cs:line 453
   at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime, RenderTarget2D target_screen) in SMAPI\Framework\SGame.cs:line 921
```
![image](https://user-images.githubusercontent.com/83290351/166106225-aa8ef1fe-64d7-4d67-860c-f5bb57ad5328.png)

**Comment by Pathoschild** [comment]
That should be fixed in CJB Item Spawner 2.2.0. Thanks for reporting it!
