### ISSUE TITLE
[CJB Item Spawner] ignore invalid items

### ISSUE THREAD

**Issue by Pathoschild** [CJBok/SDV-Mods#41]
The item spawner menu crashes with an error like this if an item is invalid (see [sample log](https://log.smapi.io/8TUtBpzV)):
> The CJBItemSpawner.Framework.ItemMenu menu crashed while drawing itself. SMAPI will force it to exit to avoid crashing the game. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary. at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (System.Collections.Generic.TKey key) <0x10e6987b0 + 0x00069> in <filename unknown>:0 at StardewValley.Object.getDescription () <0x196bb04a0 + 0x00374> in <filename unknown>:0 at CJBItemSpawner.Framework.ItemMenu.draw (Microsoft.Xna.Framework.Graphics.SpriteBatch spriteBatch) <0x196b9a320 + 0x00671> in <filename unknown>:0 at StardewModdingAPI.Framework.SGame.DrawImpl (Microsoft.Xna.Framework.GameTime gameTime) <0x18eae8000 + 0x0ce4e> in <filename unknown>:0 

Add logic to ignore invalid items.

**Comment by Pathoschild** [comment]
Here are the files for that sample log:
* [Save](https://github.com/CJBok/SDV-Mods/files/2173279/Mickey_180770102.zip)
* Mods (see parts [one](https://github.com/CJBok/SDV-Mods/files/2173282/Mods.001.zip), [two](https://github.com/CJBok/SDV-Mods/files/2173280/Mods.002.zip), [three](https://github.com/CJBok/SDV-Mods/files/2173281/Mods.003.zip))

**Comment by miome** [comment]
I am getting the same error for an object added through a JsonAssets content pack.

**Comment by Pathoschild** [comment]
Different error reported on Nexus:
```
This mod failed in the ControlEvents.KeyPressed event. Technical details:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at StardewValley.Objects.Hat.load(Int32 which)
at CJBItemSpawner.Framework.ItemMenu.<GetSpawnableItems>d__35.MoveNext() in C:\source\_Stardew\Mods.CJB\CJBItemSpawner\Framework\ItemMenu.cs:line 518
at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at CJBItemSpawner.Framework.ItemMenu..ctor(MenuTab currentTab, Int32 sortID, ItemQuality quality, ITranslationHelper i18n) in C:\source\_Stardew\Mods.CJB\CJBItemSpawner\Framework\ItemMenu.cs:line 55
at CJBItemSpawner.ModEntry.Events_KeyPressed(Object sender, EventArgsKeyPressed e) in C:\source\_Stardew\Mods.CJB\CJBItemSpawner\ModEntry.cs:line 46
at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 54
```

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming CJB Item Spawner 1.11.
